blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Vidwall Hub Official Website
    url: https://wangchujiang.com/vidwall-hub/
    about: Introduction to the Vidwall Hub app on the official website!