name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Released Tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ steps.create_tag.outputs.version }}
          release: true
          body: |
            <a target="_blank" href="https://github.com/jaywcjlove/vidwall-hub/releases/latest/" title="Vidwall Hub for macOS">
              <img alt="Vidwall Hub AppStore" src="https://jaywcjlove.github.io/sb/download/apple-download.svg" height="51">
            </a>

      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "Vidwall Hub {{version:${{ steps.create_tag.outputs.version }}}}"
          description: Vidwall Hub is a tool that makes it easy to import videos (mp4, mov) into the system wallpaper service and use them as lock screen animations through the system settings.
          keywords: Vidwall Hub,video wallpaper,lock screen animations,macOS tools,system productivity
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/vidwall-hub
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          menus:
            Home: index.html
            Vidwall: https://wangchujiang.com/vidwall/
            Apps: https://wangchujiang.com/#/app
            About: https://wangchujiang.com/#/about
          sideEffectFiles:
            - README.md
            - README.zh.md
            - CHANGELOG.md
            - CHANGELOG.zh.md
          footer: |
            <a href="https://wangchujiang.com/#/app" target="_blank">App</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}          
          EOF
      - run: npm install idoc@1 -g
      - run: idoc
      - run: cp appcast.xml dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

